name: BETA deploy s3

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: rm
        run: rm .eslintrc.yml

      - name: install
        run: npm ci
        working-directory: ./beta

      - name: build
        run: npm run build
        working-directory: ./beta

      - name: export
        run: npm run export
        working-directory: ./beta

      - name: Upload file to S3
        env:
          S3_CONTENTS_BUCKET: ${{ secrets.S3_CONTENTS_BUCKET }}
        run: |
          aws s3 sync ./out s3://$S3_CONTENTS_BUCKET/beta/ --quiet
        working-directory: ./beta
